# Values to use when running on a development box. These will be overridden
# when using the remote configuration service.
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/imrt"
  batch:
    job:
      enabled: false # Prevent Spring from starting jobs on startup.
    initialize-schema: "never" # Prevent Spring from creating the spring batch schema on startup.

logging:
  level:
    org.opentestsystem: DEBUG
    org.gitlab4j: INFO
  config: classpath:log4j2-local.xml

iis:
  retry-initial-interval: 1000
  retry-interval-multiplier: 2
  retry-max-interval: 5000
  retry-amount: 3
  imrt-page-query-limit: 1000

itembank:
  host: "${GITLAB_HOST:https://gitlab-dev.smarterbalanced.org}"
  accessToken: "${GITLAB_ACCESS_TOKEN}"
  group: "${GITLAB_GROUP}"
  webhookUrl: "${GITLAB_WEBHOOK_URL}"
  projectsToIgnore : itembankreports

server:
  port: ${IMRT_IIS_SERVER_PORT:9081}
