# Values to use when running on a development box. These will be overridden
# when using the remote configuration service.
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/imrt"
  batch:
    job:
      enabled: false # Prevent Spring from starting jobs on startup.
    initialize-schema: "never" # Prevent Spring from creating the spring batch schema on startup.

logging:
  level:
    org.opentestsystem: DEBUG
    org.gitlab4j: INFO

iis:
  retry-amount: 3
  imrt-page-query-limit: 1000
  item-validation-service-url: "http://localhost:8087"

itembank:
  host: "${GITLAB_HOST:https://gitlab-dev.smarterbalanced.org}"
  access-token: "${GITLAB_ACCESS_TOKEN}"
  group: "${GITLAB_GROUP}"
  webhook-url: "${GITLAB_WEBHOOK_URL}"
  projects-to-ignore : itembankreports

server:
  port: ${IMRT_IIS_SERVER_PORT:9081}
---
spring:
  profiles: local-development
logging:
  config: classpath:log4j2-local.xml

