# Values to use when running on a development box. These will be overridden
# when using the remote configuration service.
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/imrt"

logging:
  level:
    org.opentestsystem: DEBUG
    org.gitlab4j: INFO

iis:
  retry-initial-interval: 1000
  retry-interval-multiplier: 2
  retry-max-interval: 5000
  retry-amount: 3
  imrt-page-query-limit: 1000

server:
  port: ${IMRT_IIS_SERVER_PORT:9081}
