# Values to use when running on a development box. These will be overridden
# when using the remote configuration service.
management:
  security:
    enabled: false

security:
  basic:
    enabled: false

jwt:
  secret: ${TIMS_JWT_SECRET}

spring:
  freemarker:
    checkTemplateLocation=false:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/imrt"
    username: ${IMRT_DB_USER}
    password: ${IMRT_DB_PASSWORD}
  batch:
    job:
      enabled: false # Prevent Spring from starting jobs on startup.
    initialize-schema: "never" # Prevent Spring from creating the spring batch schema on startup.

logging:
  level:
    org.opentestsystem: INFO
    org.gitlab4j: WARN

iis:
  retry-amount: 3
  imrt-page-query-limit: 10
  item-validation-service-url: "http://localhost:8087"
  item-management-service-url: "http://localhost:8081"

itembank:
  systemUser:
    userName: "iat-imrt-ingest@smarterbalanced.org"
    fullName: "Item Ingest"
  host: "${GITLAB_HOST:https://gitlab-dev.smarterbalanced.org}"
  access-token: "${GITLAB_ACCESS_TOKEN}"
  group: "${GITLAB_GROUP}"
  webhook-url: "${GITLAB_WEBHOOK_URL}"
  projects-to-ignore : itembankreports
  api-version: "/api/v4"
  projects-per-page: 50
  delete-item-git-page-size: 50
  delete-sync-disabled: false
  tims:
    exchange: "iat_item_event_exchange"
    queue: "imrt_item_event_queue"
    eventKey: "iat.item.event.*"

server:
  port: ${IMRT_IIS_SERVER_PORT:9081}

---
spring:
  profiles: local-development
logging:
  config: classpath:log4j2-local.xml
iis:
  ignore-validate: false
  ignore-webhook-creation: true
  validation-queue-concurrent-consumers: 2
  sync-job-item-sync-concurrent-consumers: 2
