version: '3'
services:
    rabbitmq:
        container_name: rabbit-server
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - spring-cloud-network
        healthcheck:
          test: ["CMD", "rabbitmqctl", "node_health_check"]
          interval: 30s
          timeout: 5s
          retries: 3
        logging:
            driver: json-file
    configuration-service:
        container_name: configuration-service
        image: @dockerTagBase@/configuration-service:@configServerVersion@
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
          interval: 30s
          timeout: 5s
          retries: 3
        environment:
          CONFIG_SERVICE_REPO: "file://tmp"
          SPRING_CLOUD_BUS_ENABLED: "false"
          MANAGEMENT_HEALTH_RABBIT_ENABLED: "false"
        expose:
            - 8888
        ports:
            - 8888:8888
        networks:
            - spring-cloud-network
        volumes:
            - @USER_HOME@/sbac/imrt-config-repo:/tmp
        logging:
            driver: json-file
    ap-imrt-iis-service:
        container_name: ap-imrt-iis-service
        image: @dockerTagBase@/ap-imrt-iis:@version@
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
          interval: 30s
          timeout: 5s
          retries: 3
        environment:
            CONFIG_SERVICE_ENABLED: "true"
            CONFIG_SERVICE_URL: "http://configuration-service:8888"
            # Assume gitlab is running on the local dev machine, outside of docker compose
            GITLAB_HOST: "http://docker.for.mac.host.internal"
            # Empty values are taken from the host environment
            GITLAB_ACCESS_TOKEN:
            GITLAB_GROUP:
            GITLAB_WEBHOOK_URL:
            SPRING_RABBITMQ_HOST: "rabbitmq"
            SPRING_DATASOURCE_URL: "jdbc:postgresql://docker.for.mac.host.internal:5432/imrt"
            SPRING_DATASOURCE_USERNAME: "imrt-ingest"
            SPRING_DATASOURCE_PASSWORD:
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
        depends_on:
            - configuration-service
            - rabbitmq
        logging:
            driver: json-file

networks:
    spring-cloud-network:
        driver: bridge

